### PR TITLE
Setup Project

### PR DESCRIPTION
**Pull request by Speuce**
Introduced all the basic framework for Docker, Django, Vue and Postgres. For issue #23.

Reviewers: See [these instructions](https://github.com/Speuce/JAMCo/blob/setup-project/docs/setup.md) for instructions to follow, ensure that they work for you.

### CODE REVIEW

**Comment by jaredwebber** [comment]
Setup instructions work for me, just a couple comments/observations:
1. We might want to add a step 0 which is: Start docker daemon, as it's required to be running before opening the dev containers (step 3)
2. Do we want to add a prettierrc (I noticed my local markdown linting is different)
3. I also noticed that if I open the backend dev container, the frontend also launches, and vice-versa, is there a reason to launch them separately?

**Comment by Speuce** [comment]
> Setup instructions work for me, just a couple comments/observations:
> 
> 1. We might want to add a step 0 which is: Start docker daemon, as it's required to be running before opening the dev containers (step 3)
> 2. Do we want to add a prettierrc (I noticed my local markdown linting is different)
> 3. I also noticed that if I open the backend dev container, the frontend also launches, and vice-versa, is there a reason to launch them separately?

1. Good point. Will add.
2. Markdown linting? Hah I did the markdown in github's browser editor. We have a prettierrc for js, but it's empty for now. I guess  I should probably add to that. 
3. Yeah so the reason you'd want to launch them separately is to develop in them. If you launch the backend container in vscode, you'll only be able to edit the backend files. If you start the frontend container from vscode after the backend container, it will simply restart the container and attach your vscode instance to the container in order to make changes for the frontend.

**Comment by jaredwebber** [comment]
> 2. Markdown linting? Hah I did the markdown in github's browser editor. We have a prettierrc for js, but it's empty for now. I guess  I should probably add to that.
> 3. Yeah so the reason you'd want to launch them separately is to develop in them. If you launch the backend container in vscode, you'll only be able to edit the backend files. If you start the frontend container from vscode after the backend container, it will simply restart the container and attach your vscode instance to the container in order to make changes for the frontend.
>    Technically, you could launch the containers without vscode at all, (using docker desktop), and edit the files on local, but then you would need to install the dev dependencies (eslint, python environment, pylint etc) in order for linting/intellisense/imports to work correctly on your local. By attaching via vscode you're coding within the container itself, which has all these dependencies added. (The containers files are automatically synced with the files on your local machine)

Sounds good the separate launch options make sense, though curious if it would make sense to have 1 script to launch both, allowing editing of both from the root directory in vscode (definitely not urgent though). I have prettier running locally on save and it formats markdown 🤷 - I could try and turn it off though doesn't matter

**Comment by Speuce** [comment]
> > 2. Markdown linting? Hah I did the markdown in github's browser editor. We have a prettierrc for js, but it's empty for now. I guess  I should probably add to that.
> > 3. Yeah so the reason you'd want to launch them separately is to develop in them. If you launch the backend container in vscode, you'll only be able to edit the backend files. If you start the frontend container from vscode after the backend container, it will simply restart the container and attach your vscode instance to the container in order to make changes for the frontend.
> >    Technically, you could launch the containers without vscode at all, (using docker desktop), and edit the files on local, but then you would need to install the dev dependencies (eslint, python environment, pylint etc) in order for linting/intellisense/imports to work correctly on your local. By attaching via vscode you're coding within the container itself, which has all these dependencies added. (The containers files are automatically synced with the files on your local machine)
> 
> Sounds good the separate launch options make sense, though curious if it would make sense to have 1 script to launch both, allowing editing of both from the root directory in vscode (definitely not urgent though). I have prettier running locally on save and it formats markdown 🤷 - I could try and turn it off though doesn't matter

Yeah.. working in a joint environment is something vscode wants to implement but as of now the separate environments is the suggested (and only) method of dealing with multiple containers.

We could make our own joint container and launch both services from within it, but then you run into problems with usage between dev and prod. The frontend container is _only_ to run a local dev server to serve the frontend files with hot reloading. In production, webpack bundles everything into a single html/js/css file, and therefore we don't need the frontend server.

**Review by jaredwebber — APPROVED** [review]
LGTM

**Pull request merged**
