### PR TITLE
Document coding style

### LINKED ISSUE #167: Document Coding Style
Add some documentation to the readme as to the coding style we enforce via front and back end linting

### PR DESCRIPTION
**Pull request by drkitt**
## Tickets
Closes #167

## Summary Of Changes
Added a section on our coding style to the readme

## Notes for Reviewers
Click on the branch name (on this page, on the line below the PR title) to view the readme in its natural habitat

### CODE REVIEW

**Review by jaredwebber — COMMENTED** [review]
Should probably add `black` and `flake8` for backend formatting (Linting GHA found [here](https://github.com/Speuce/JAMCo/blob/master/.github/workflows/backend_lint.yml)), as well as `eslint` and `prettier` for frontend ([gha here](https://github.com/Speuce/JAMCo/blob/master/.github/workflows/node.js.yml#L54))

**Review by Speuce — CHANGES_REQUESTED** [review]
Can we list some specific rules within the airbnb style guide, as well as some descriptions of the python code style (such as spacing style), as well as more detailed descriptions of what the aforementioned warnings mean?

Was thinking ~1-2 paragraphs for this section to be specific enough for the grader.

**Comment by drkitt** [comment]
@Speuce I wrote a bunch of stuff about Pylint (see [this commit](https://github.com/Speuce/JAMCo/pull/177/commits/2c7b91147cce3c0a93b75b3d86101c0fb1de3c5f) before realizing that it's not included in our GitHub Actions setup and doesn't seem to be set up to be run locally. Can you clarify whether we're using Pylint?

**Review by LokiFrostGiant — DISMISSED** [review]
Can we mention that in backend, functions must be separated by one blank line, and classes must be separated by two blank lines? I know there's something similar on line 106, but this is what is minimum vs what is maximum.

Also, should we mention anything about specifying a function's return type?

**Comment by jaredwebber** [comment]
> > Can we mention that in backend, functions must be separated by one blank line, and classes must be separated by two blank lines? I know there's something similar on line 106, but this is what is minimum vs what is maximum.
> 
> > 
> 
> > Also, should we mention anything about specifying a function's return type?
> 
> 
> 
> Sure thing, just added a point about blank lines.
> 
> 
> 
> I don't have anything in there about specifying functions' return types because we don't do it consistently. (Looks like we don't do it at all in the view layer and we do it some/most of the time in the business and query layers.) I could put something like, "specify the return type if it's not obvious from the contents of the function," though.

imo id avoid drawing attention to types, since we rarely define variable types from what i remember - but whatever y'all decide is fine

**Review by jaredwebber — APPROVED** [review]
Looks like enough detail to me

**Review by Speuce — APPROVED** [review]

**Pull request merged**
